import type { Metadata } from "next";
import { Toaster } from "react-hot-toast";
import Header from "@/components/header";
import "../assets/styles/globals.scss";
import "../assets/styles/reset.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header />

        {children}
        <Toaster position="top-center" />
      </body>
    </html>
  );
}
